### ISSUE TITLE
`SecretsAPI.Resolve` does not support items names that contain `.`

### ISSUE THREAD

**Issue by pgavlin** [1Password/onepassword-sdk-go#105]
### Scenario & Reproduction Steps

Run [this program](https://gist.github.com/pgavlin/c4e36a05d62bee6d1802be609430e4e9) with an appropriate service token and attempt to fetch an item with `.` characters in the name:

```console
$ OP_SERVICE_ACCOUNT_TOKEN=... go run main.go "op://Test Vault/foo.bar.baz/username"
```

### Actual Behavior

The program logs an error:

```console
2024/07/15 10:31:41 error resolving secret reference: secret reference has invalid format - must be "op://<vault>/<item>/[section/]field"
exit status 1
```

### Expected Behavior

The program fetches the item's contents and exists successfully.

### SDK version

v0.1.0-beta.10

**Comment by hculea** [comment]
This should now be fixed with [SDK release 0.1.0-beta.11](https://github.com/1Password/onepassword-sdk-go/releases/tag/v0.1.0-beta.11).

Feel free to reopen if you run into any other such issues.
