### ISSUE TITLE
Support adding tags to Items

### ISSUE THREAD

**Issue by Otterpohl** [1Password/onepassword-sdk-go#86]
### Use Case

I want to be able to programmatically create items with tags as seen in [connect-sdk-go](https://github.com/1Password/connect-sdk-go/blob/336b23f33782b19e6ca811ed7c61906272c8440d/onepassword/items.go#L87C2-L87C44)

### Requirements and desired behavior

copy the implementation from [connect-sdk-go](https://github.com/1Password/connect-sdk-go/blob/336b23f33782b19e6ca811ed7c61906272c8440d/onepassword/items.go#L87C2-L87C44)

**Comment by Marton6** [comment]
Hi @Otterpohl. Thank you for filing this feature request. Creating items with specific tags indeed seems like a useful feature for the SDKs. We will definitely consider adding this to our roadmap.

**Comment by sadiaazmal** [comment]
Hi @Otterpohl,
I'm Sadia, the product manager leading the SDK initiative, it’s nice to meet you. Thank you submitting your feature request. Could you provide more details on how you currently use tags and what specific goals you're hoping to achieve? This information will help our team better understand your needs, ensuring we can deliver the right solution to address them effectively.

**Comment by Otterpohl** [comment]
I'm not expecting anything novel out of this request, just support for specifying tags in the SDK just like you do for the connect SDK. 

We use tags as metadata for organising credentials.

**Comment by MOmarMiraj** [comment]
Hey @Otterpohl 

With the release of v0.1.2 of the Go SDK, tags on Items are now supported!

I will close this issue and if theres any issues with the tags, please feel free to open up another issue.
